In [2]:
import pandas as pd

In [3]:
data=pd.read_html("https://www.nparks.gov.sg/nature/species-list/lepidoptera-butterflies")

In [4]:
# First table
data[0]

,Unnamed: 0,Category,Abbreviation,Criteria
0,Not Threatened,Least Concern,LC,Not approaching threatened status
1,Not Threatened,Near-Threatened,NT,Close to becoming threatened or may meet the c...
2,Threatened,Vulnerable,VU,"There are more than 250 but fewer than 1,000 m..."
3,Threatened,Endangered,EN,There are fewer than 250 mature individuals an...
4,Threatened,Critically Endangered,CR,"There are fewer than 50 mature individuals, OR..."
5,Extirpation & Extinction,Presumed Nationally Extinct,NEx,The species is extinct (extirpated) within Sin...
6,Extirpation & Extinction,Globally Extinct,EX,"The species is extinct all over the world, bot..."
7,Other Categories,Data Deficient,DD,Inadequate information to make an informed ass...
8,Other Categories,Not Applicable,NaN,Species that are not eligible for assessment a...
9,Other Categories,Not Evaluated,NE,Species that are possibly eligible for assessm...
10,Other Categories,Not Listed,NL,Species not listed in the records (in the IUCN...

In [5]:
# Second table
data[1]

,Family,Taxon Name,Common Name,Origin,RDB2,RDB3
0,Papilionidae,Troides helena cerberus,Common Birdwing,Native,VU,VU
1,Papilionidae,Troides amphrysus ruficollis,Malayan Birdwing,Native,NEx,DD
2,Papilionidae,Pachliopta aristolochiae asteris,Common Rose,Native,VU,NT
3,Papilionidae,Papilio clytia clytia,Common Mime,Native,Not Listed,LC
4,Papilionidae,Papilio paradoxa aenigma,Great Blue Mime,Native,NEx,NEx
...,...,...,...,...,...,...
482,Hesperiidae,Baoris oceia,Paintbrush Swift,Native,Not Listed,LC
483,Hesperiidae,Caltoris cormasa,Full Stop Swift,Native,Not Listed,LC
484,Hesperiidae,Caltoris bromus bromus,Extra Spot Swift,Uncertain,Not Listed,DD
485,Hesperiidae,Caltoris philippina philippina,Philippine Swift,Native,Not Listed,VU
486,Hesperiidae,Caltoris malaya,Malayan Swift,Native,NEx,NT

In [14]:
# How long is one table
len(data[0])

11

In [21]:
# How long is second table
len(data[1])

487

In [18]:
# names of columns of 1st table
data[0].iloc[0]

Unnamed: 0                         Not Threatened
Category                            Least Concern
Abbreviation                                   LC
Criteria        Not approaching threatened status
Name: 0, dtype: object

In [22]:
# names of columns of 2nd table
data[1].iloc[0]

Family                    Papilionidae
Taxon Name     Troides helena cerberus
Common Name            Common Birdwing
Origin                          Native
RDB2                                VU
RDB3                                VU
Name: 0, dtype: object

In [34]:
# common names
data[1].iloc[0][2]

'Common Birdwing'

In [35]:
# for loop
data[1].loc[:,'Common Name']

0       Common Birdwing
1      Malayan Birdwing
2           Common Rose
3           Common Mime
4       Great Blue Mime
             ...
482    Paintbrush Swift
483     Full Stop Swift
484    Extra Spot Swift
485    Philippine Swift
486       Malayan Swift
Name: Common Name, Length: 487, dtype: object

In [36]:
# return a slice, interested to get "Taxon Name", "Common Name"
data[1].loc[:,'Taxon Name':'Common Name']

                           Taxon Name       Common Name
0             Troides helena cerberus   Common Birdwing
1        Troides amphrysus ruficollis  Malayan Birdwing
2    Pachliopta aristolochiae asteris       Common Rose
3               Papilio clytia clytia       Common Mime
4            Papilio paradoxa aenigma   Great Blue Mime
..                                ...               ...
482                      Baoris oceia  Paintbrush Swift
483                  Caltoris cormasa   Full Stop Swift
484            Caltoris bromus bromus  Extra Spot Swift
485    Caltoris philippina philippina  Philippine Swift
486                   Caltoris malaya     Malayan Swift

[487 rows x 2 columns]

In [47]:
df=data[1]

In [48]:
df

,Family,Taxon Name,Common Name,Origin,RDB2,RDB3
0,Papilionidae,Troides helena cerberus,Common Birdwing,Native,VU,VU
1,Papilionidae,Troides amphrysus ruficollis,Malayan Birdwing,Native,NEx,DD
2,Papilionidae,Pachliopta aristolochiae asteris,Common Rose,Native,VU,NT
3,Papilionidae,Papilio clytia clytia,Common Mime,Native,Not Listed,LC
4,Papilionidae,Papilio paradoxa aenigma,Great Blue Mime,Native,NEx,NEx
...,...,...,...,...,...,...
482,Hesperiidae,Baoris oceia,Paintbrush Swift,Native,Not Listed,LC
483,Hesperiidae,Caltoris cormasa,Full Stop Swift,Native,Not Listed,LC
484,Hesperiidae,Caltoris bromus bromus,Extra Spot Swift,Uncertain,Not Listed,DD
485,Hesperiidae,Caltoris philippina philippina,Philippine Swift,Native,Not Listed,VU
486,Hesperiidae,Caltoris malaya,Malayan Swift,Native,NEx,NT

In [53]:
# interested to get the from Common Name Column, "Common Birdwing"
filtered_df=df.loc[df['Common Name']=="Dark Glassy Tiger"]

In [54]:
filtered_df

,Family,Taxon Name,Common Name,Origin,RDB2,RDB3
55,Nymphalidae,Parantica agleoides agleoides,Dark Glassy Tiger,Native,Not Listed,LC

In [55]:
# interested to get from the first table what is 'LC'
df2=data[0]

In [56]:
df2

,Unnamed: 0,Category,Abbreviation,Criteria
0,Not Threatened,Least Concern,LC,Not approaching threatened status
1,Not Threatened,Near-Threatened,NT,Close to becoming threatened or may meet the c...
2,Threatened,Vulnerable,VU,"There are more than 250 but fewer than 1,000 m..."
3,Threatened,Endangered,EN,There are fewer than 250 mature individuals an...
4,Threatened,Critically Endangered,CR,"There are fewer than 50 mature individuals, OR..."
5,Extirpation & Extinction,Presumed Nationally Extinct,NEx,The species is extinct (extirpated) within Sin...
6,Extirpation & Extinction,Globally Extinct,EX,"The species is extinct all over the world, bot..."
7,Other Categories,Data Deficient,DD,Inadequate information to make an informed ass...
8,Other Categories,Not Applicable,NaN,Species that are not eligible for assessment a...
9,Other Categories,Not Evaluated,NE,Species that are possibly eligible for assessm...
10,Other Categories,Not Listed,NL,Species not listed in the records (in the IUCN...

In [59]:
filtered_df2=df2.loc[df2['Abbreviation']=='LC']

In [60]:
filtered_df2

,Unnamed: 0,Category,Abbreviation,Criteria
0,Not Threatened,Least Concern,LC,Not approaching threatened status

In [61]:
# export table to .csv file
df.to_csv('butterflyList.csv', index = False)

In [62]:
df2.to_csv('conservationStatus.csv',index=False)